### ISSUE TITLE
Cannot access mqtt proxy from outside docker

### ISSUE THREAD

**Issue by blqck11** [gschmutz/iot-vehicle-tracking-demo#3]
hi, 
the problem here is how to write mqtt data using mosquito for exemple to confluent mqtt proxy from outside docker???
this is the config of the proxy which is in a docker.
`  kafka-mqtt:
    container_name: kafka-mqtt
    hostname: kafka-mqtt
    image: confluentinc/cp-kafka-mqtt:latest
    network_mode: host
    ports:
      - 1883:1883
    environment:
      KAFKA_MQTT_BOOTSTRAP_SERVERS: PLAINTEXT://localhost:9092
      KAFKA_MQTT_ADVERTISED_LISTENERS: http://0.0.0.0:1883
      KAFKA_MQTT_LISTENERS: 0.0.0.0:1883
      KAFKA_MQTT_TOPIC_REGEX_LIST: mqtt.temperature:.*temperature
`

when i try mosquitto_pub -h 127.0.0.1 -p 1883 -t mqtt.temperature -q 2 -m "5" 
nothing happens in the topic no data is inserted , but in mosquitto sub the message is displayed.
any help on this ??

**Comment by gschmutz** [comment]
@blqck11 sorry for the late reply, I did not see your issue until yesterday. Not sure if it is still an open issue/question, but I will answer it anyway. 

If I add the MQTT Proxy using the Platys generator, which creates the docker-compose.yml, it looks like this

```
  kafka-mqtt-1:
    image: confluentinc/cp-kafka-mqtt:6.0.0
    container_name: kafka-mqtt-1
    hostname: mqtt-proxy
    ports:
      - 1882:1882
    environment:
      KAFKA_MQTT_TOPIC_REGEX_LIST: truck_position:.*position
      KAFKA_MQTT_LISTENERS: 0.0.0.0:1882
      KAFKA_MQTT_BOOTSTRAP_SERVERS: kafka-1:19092,kafka-2:19093,kafka-3:19094
      KAFKA_MQTT_CONFLUENT_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - ./data-transfer:/data-transfer
    restart: unless-stopped
```

With that I'm able to produce to the proxy instead of mosquitto and the data shows up in the kafka topic. I'm also able to use `mosquito_pub` to publish data.
But I don't think that the MQTT Proxy supports subscription as well, I believe it only support publishing, and if I use `mosquitto_sub` I'm able to connect but won't get any data, even though it is sent to the `truck_position` Kafka topic.
